generation:
  num_subsamples: 30
  num_demos: 1 
  num_prompts_per_subsample: 5
  model: 
    name: GPT
    gpt_config: 
      model: gpt-3.5-turbo-1106
      temperature: 0.9
      max_tokens: 500
      top_p: 0.9
      frequency_penalty: 0.0
      presence_penalty: 0.0

evaluation:
  num_subsamples: 20
  num_inputs: 1
  num_outputs_per_subsample: 3
  method: likelihood
  model:
    name: GPT
    gpt_config:
      model: gpt-3.5-turbo-1106
      temperature: 0.7
      max_tokens: 500
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
score:
  num_scores: 1
  model: 
    name: GPT
    gpt_config:
      model: gpt-3.5-turbo-1106
      temperature: 0.7
      max_tokens: 200
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0

